server:
  port: 5001

spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/danbee
#    url: jdbc:mariadb://223.130.140.173:3306/danbee
#    username: root
#    password: password
#    driver-class-name: org.mariadb.jdbc.Driver
  datasource:
#    url: jdbc:mysql://localhost:3306/skens_poc
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mariadb://101.79.8.7:3306/skens_apigw?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure : ERROR
    org.springframework.web : DEBUG

