server:
  port: 5001

spring:
  datasource:
#    url: jdbc:mariadb://223.130.140.173:3306/danbee
#    username: root
#    password: password
#    driver-class-name: org.mariadb.jdbc.Driver

#    local - spk api gateway DB
#    url: jdbc:mariadb://localhost:3306/spk-apigw
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver

#    SK E&S
#    url: jdbc:mariadb://101.79.8.7:3306/skens_apigw?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&characterEncoding=UTF-8
#    username: root
#    password: password
#    driver-class-name: org.mariadb.jdbc.Driver


#  sfmi server DB
#    url: jdbc:mariadb://211.191.186.224:3306/sai_sfmi
#    username: root
#    password: password
#    driver-class-name: org.mariadb.jdbc.Driver

#  spk CDB - sfmi
    url: jdbc:mariadb://223.130.138.55:3306/sai_sfmi
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

#  aicc01 DB
#    url: jdbc:mariadb://localhost:3306/sai
#    username: root
#    password: password
#    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure : ERROR
    org.springframework.web : INFO
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
  file:
    name: logs/sai.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss


naver:
  stt:
    key:
      id: 156e1637b8d8489cb4f6f26cab8ba888

bp:
  api:
    key: 9845y2guwhvleajtp2