server:
  port: 5001
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: tlavmfzl1!

spring:
  datasource:
#    url: jdbc:mariadb://223.130.140.173:3306/danbee
#    username: root
#    password: password
#    driver-class-name: org.mariadb.jdbc.Driver

#    local - spk api gateway DB
#    url: jdbc:mariadb://localhost:3306/spk-apigw
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver

#    SK E&S
#    url: jdbc:mariadb://101.79.8.7:3306/skens_apigw?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&characterEncoding=UTF-8
#    username: root
#    password: password
#    driver-class-name: org.mariadb.jdbc.Driver


#  sfmi server DB
#    url: jdbc:mariadb://211.191.186.224:3306/sai_sfmi
#    username: root
#    password: password
#    driver-class-name: org.mariadb.jdbc.Driver

#  spk CDB - sfmi
    url: jdbc:mariadb://223.130.138.55:3306/sai_sfmi
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure : ERROR
    org.springframework.web : DEBUG

